var DiasSemana= [
   {
      "Valor":"0",
      "Dia":"Todos"
   },
   {
      "Valor":"Lunes",
      "Dia":"Lunes"
   },
   {
      "Valor":"Martes",
      "Dia":"Martes"
   },
   {
      "Valor":"Miercoles",
      "Dia":"Miercoles"
   },
   {
      "Valor":"Jueves",
      "Dia":"Jueves"
   },
   {
      "Valor":"Viernes",
      "Dia":"Viernes"
   },
   {
      "Valor":"Sabado",
      "Dia":"Sabado"
   }
];




var Horarios = [
   {
      "Hora":"30/12/1899 16:00:00",
      "Maestro":"Elizabeth Blanca Cuadros Loayza",
      "Curso":"Antiguo Testamento 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153670",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/F79bKnIcj6qEc5ZqVBRxq3",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Felizabeth.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"AntiguoTestamento2",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 18:00:00",
      "Maestro":"Linda Medina Morales",
      "Curso":"Historia Familiar",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154211",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/JKFVRAHEe748dGCathvhF5",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Flinda.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"HistoriaFamiliar",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Liliana Empertariz Tirado Santa Cruz",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153678",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/GDLowu4OIRw2l2vhuA1woa",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fliliana.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Rocio Reyes",
      "Curso":"El Evangelio y Vida Productiva",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153677",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/HUJkrfiKZfRIiPst6YepuE",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Frocio.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"ElEvangelioyVidaProductiva",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Alejandro David Piscoya Leng",
      "Curso":"Ense\u00F1anzas y Doctrina del Libro de Morm\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153675",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/L483IQpIbC4GKPq8z5yhPO",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fdavid.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"Ense\u00F1anzasyDoctrinadelLibrodeMorm\u00F3n",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Pedro Alberto N\u00FA\u00F1ez C\u00F3ndor",
      "Curso":"Estudio de las Escrituras",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154214",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/IsjkCI7iG1qAMc5dAugfxk",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fpedro.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"EstudiodelasEscrituras",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Spencer Valle Valencia",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153673",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Ic3PY01oD9mECHyt9mhRus",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fspencer.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Nancy Julca Urbina",
      "Curso":"Preparemos un Matrimonio Eterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154213",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/F28BA5f5yamBSllzv6PrS4",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fnancy.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"PreparemosunMatrimonioEterno",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 19:30:00",
      "Maestro":"Luis Antonio Salazar Marcelo",
      "Curso":"Presidentes de la Iglesia",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154215",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/F5w8JJcMUUvAf0PBtZSi6L",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fluissalazar.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"PresidentesdelaIglesia",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Victor Calderon",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153710",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/DnSJyeHTFYsHWSBTWrWSEG",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fvictor.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Ivan Brice\u00F1o Castro",
      "Curso":"Edifiquemos Matrimonio Eterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154217",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/FBocQKbJkou8WlMS8IbutV",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fivan.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"EdifiquemosMatrimonioEterno",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Jorge Ricapa Feliciano",
      "Curso":"Jesucristo y el Evangelio Sempiterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153712",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/IvWLw5wvAF30aYRTdkcm19",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fjorgericapa.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"JesucristoyelEvangelioSempiterno",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Gustavo Medina Lora",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153709",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/H8yBRT7wEmeDcS2VMXhma3",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fgustavo.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Martes",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":1
   },
   {
      "Hora":"30/12/1899 6:00:00",
      "Maestro":"Carlos M\u00E1x Riva Coral",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153715",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/C9MOIdtG7Ms2e57upgkfq1",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fcarlosriva.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"AM",
      "Dia":"Miercoles",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Jos\u00E9 Luis Valle Cabrera",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153716",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/DrZalTb5Q7H6Zrzf6yjrUC",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fjosevalle.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Emanuel Rodriguez Fernandez",
      "Curso":"Coro Avanzado",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154218",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/D6jyCoR3Dyx4R1LhBTDvRH",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Femanuel.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"CoroAvanzado",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Carlos Alberto Pujay Ortiz",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153718",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Dop9ugKmtGDDqaBa7tfqnP",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fcarlospujay.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Sahara Jara  Casazola",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153717",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Beba40hTd7uHWiborr4PpH",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fsahara.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 20:30:00",
      "Maestro":"Sandra Paola Pino Huaman",
      "Curso":"El Evangelio y Vida Productiva",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154208",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/IkbgQusNOv5DoxYqaFIlvJ",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fsandrapino.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"ElEvangelioyVidaProductiva",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 20:30:00",
      "Maestro":"Manuel y Tatiana Navarro",
      "Curso":"Preparemos un Matrimonio Eterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154219",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/ILLEgX8fXTz6fftlUvGsN3",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fmanuel.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"PreparemosunMatrimonioEterno",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 21:00:00",
      "Maestro":"Miguel Herrera",
      "Curso":"Las Mujeres de las escrituras",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154224",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/KLAy6uh341zGZExF6cxz2f",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fmiguelherrera.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Miercoles",
      "CursoCorto":"LasMujeresdelasescrituras",
      "NumeroDia":2
   },
   {
      "Hora":"30/12/1899 6:30:00",
      "Maestro":"Jorge Erickson Paz Diaz",
      "Curso":"La Familia Eterna",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153906",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Ci9FwTvEJ202nSmQ0Agmx1",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fjorgepaz.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"AM",
      "Dia":"Jueves",
      "CursoCorto":"LaFamiliaEterna",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 16:00:00",
      "Maestro":"Elizabeth Blanca Cuadros Loayza",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154292",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/KyZdCuEY6Nl3CjgSUmvDDx",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Felizabeth.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Roberto Polanco",
      "Curso":"Fundamentos de la Restauraci\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153907",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/KfunV3ZI1Q7GxgYtTsRL9C",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Froberto.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"FundamentosdelaRestauraci\u00F3n",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 19:30:00",
      "Maestro":"Enrique Aramis Cordova Torres",
      "Curso":"Coro",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153909",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/JlXDPs7MbqZ0W0nSGWhX6L",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fenrique.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"Coro",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Kenny Quispit\u00FApac",
      "Curso":"El Evangelio y Vida Productiva",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153913",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Bj8nlfBfrveK3bWg8WNnrr",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fkenny.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"ElEvangelioyVidaProductiva",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Ana Luc\u00EDa Aguilar",
      "Curso":"Himnos de los Santos de los \u00DAltimos D\u00EDas",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154220",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/ChhrHIVbq4Y9AO0rML1ZOm",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fana.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"HimnosdelosSantosdelos\u00DAltimosD\u00EDas",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Gabriel Arturo Romero Perico",
      "Curso":"Historia de los Santos",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153911",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/BTOppDY3ScaLkUFFZZPZsH",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fgabriel.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"HistoriadelosSantos",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Carlos Rojas Baltazar",
      "Curso":"Historia de los Santos",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153934",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/J31MLGTVLBf0IzdlQL5yHL",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fcarlosrojas.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"HistoriadelosSantos",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Sandra Tacza Lume",
      "Curso":"Preparaci\u00F3n Misional",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153932",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/HOCkcYJgmKd4bFjG12LZPf",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fsandratacza.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"Preparaci\u00F3nMisional",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:30:00",
      "Maestro":"Lesseps Gonzales Ravines",
      "Curso":"Jesucristo y el Evangelio Sempiterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153938",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/E0wk7SdkjZv1cT244yD5HK",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Flesseps.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"JesucristoyelEvangelioSempiterno",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 20:30:00",
      "Maestro":"Anyd Santillan",
      "Curso":"La Familia Eterna",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153937",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/LFE0GKCYbj20zxdE3GiRNm",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fanyd.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"LaFamiliaEterna",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 21:00:00",
      "Maestro":"Luis Flores Le\u00F3n",
      "Curso":"El Divino Don de Perdon (hibrida)",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154011",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/GPa4LLsXCTu506TcqgY8KI",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fluisflores.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Jueves",
      "CursoCorto":"ElDivinoDondePerdon(hibrida)",
      "NumeroDia":3
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Carlos Alfredo Rodriguez Tito",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153943",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/HloPBOAUJPu0rz6I5k8nSw",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fcarlosrodriguez.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Viernes",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":4
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Julio C\u00E9sar Reyes Cubas",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153944",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/ImgGbTfRkDwJ6MwfQ5efjd",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fjuliocesar.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Viernes",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":4
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Leonid y Susan Quispe",
      "Curso":"Historia de los Santos",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153949",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/KLale04m9zmGD1ku5fgSkT",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fleonid.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Viernes",
      "CursoCorto":"HistoriadelosSantos",
      "NumeroDia":4
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Rudy Serna Cajaleon",
      "Curso":"Jesucristo y el Evangelio Sempiterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153946",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Go9QQaxiWcbLQ1U7cwippP",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Frudy.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Viernes",
      "CursoCorto":"JesucristoyelEvangelioSempiterno",
      "NumeroDia":4
   },
   {
      "Hora":"30/12/1899 20:30:00",
      "Maestro":"M\u00F3nica Isabel Gonz\u00E1les P\u00E9rez",
      "Curso":"Fundamentos de la Restauraci\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154031",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Lcg3RYXG8qw3UHXdnQpTC1",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fmonica.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Viernes",
      "CursoCorto":"FundamentosdelaRestauraci\u00F3n",
      "NumeroDia":4
   },
   {
      "Hora":"30/12/1899 20:30:00",
      "Maestro":"Erick John Rojas Cornejo",
      "Curso":"La Familia Eterna",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153951",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Ldy626hfd2S5ippvIKrtTy",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Ferick.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Viernes",
      "CursoCorto":"LaFamiliaEterna",
      "NumeroDia":4
   },
   {
      "Hora":"30/12/1899 10:00:00",
      "Maestro":"Piero Alfredo Guzm\u00E1n Mora",
      "Curso":"Antiguo Testamento 1",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153668",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/BI6QVglrtYC8hKwAxxPPky",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fpiero.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"AM",
      "Dia":"Sabado",
      "CursoCorto":"AntiguoTestamento1",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 10:00:00",
      "Maestro":"Samuel Arana Araujo",
      "Curso":"Fundamentos de la Restauraci\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153954",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/DfT33Fu1dgLH7ESN7D1bH4",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fsamuel.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"AM",
      "Dia":"Sabado",
      "CursoCorto":"FundamentosdelaRestauraci\u00F3n",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 7:00:00",
      "Maestro":"Aaron Pablo Escate Cabides",
      "Curso":"Ense\u00F1anzas y Doctrina del Libro de Morm\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153952",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/KtS6BBNwQvu4wIH9hliY0O",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Faaron.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"AM",
      "Dia":"Sabado",
      "CursoCorto":"Ense\u00F1anzasyDoctrinadelLibrodeMorm\u00F3n",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 7:00:00",
      "Maestro":"Moises Mamani Molina",
      "Curso":"La Familia Eterna",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153953",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/LwVES7DOxNIKUnFY7XTGox",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fmoises.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"AM",
      "Dia":"Sabado",
      "CursoCorto":"LaFamiliaEterna",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 16:00:00",
      "Maestro":"Samuel Arana Araujo",
      "Curso":"Fundamentos de la Restauraci\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153955",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/GF3vXOHhrIq4pPOOJScFZ9",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fsamuel.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"FundamentosdelaRestauraci\u00F3n",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 16:30:00",
      "Maestro":"Gian Pierre Lazo Chavez",
      "Curso":"Jesucristo y el Evangelio Sempiterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153956",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/HLijFk0ju7P6gTSC638Ve0",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fgian.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"JesucristoyelEvangelioSempiterno",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 17:00:00",
      "Maestro":"Sheyla Brillyc Revolo Montalvo",
      "Curso":"Ense\u00F1anzas y Doctrina del Libro de Morm\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154015",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/FH8eLSio90hLGVpF74ssje",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fsheyla.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"Ense\u00F1anzasyDoctrinadelLibrodeMorm\u00F3n",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 17:30:00",
      "Maestro":"C\u00E9sar Augusto Paulino Sandoval",
      "Curso":"Ense\u00F1anzas y Doctrina del Libro de Morm\u00F3n",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154018",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/F41WouqRvm569Akp1kOC2b",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fcesar.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"Ense\u00F1anzasyDoctrinadelLibrodeMorm\u00F3n",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 17:30:00",
      "Maestro":"Miguel Alejandro Pinto Gonz\u00E1les",
      "Curso":"Historia de los Santos",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154020",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Gfm6DO44ZqZIhcUrqe7U3v",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fmiguelpinto.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"HistoriadelosSantos",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 18:00:00",
      "Maestro":"Luis Flores Le\u00F3n",
      "Curso":"Doctrina y Convenios 2",
      "EnlaceInscripcion":"http://bit.ly/DC2-LF-S6",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/IgqI679YaAs8VaA697ijI1",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fluisflores.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"DoctrinayConvenios2",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Oskar Junchaya Castro",
      "Curso":"La Familia Eterna",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154022",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Cs6oJqoKpiRHD6LnEaajaS",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Foskar.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"LaFamiliaEterna",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Alex y Flor Arangoitia",
      "Curso":"La Familia Eterna",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154024",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/L7gRfUVpNWmIZqgOlT2uHJ",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Falex.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"LaFamiliaEterna",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 19:00:00",
      "Maestro":"Veronica Bardales Velasquez",
      "Curso":"Las Mujeres de las escrituras",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154221",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/Fu3JYiD4ZWXAbDgRg2dlAH",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fveronica.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"LasMujeresdelasescrituras",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Luis Flores Le\u00F3n",
      "Curso":"El Divino Don de Perdon (hibrida)",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1153920",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/BEM6qedv0VH7EN5h4UH9bT",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fluisflores.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"ElDivinoDondePerdon(hibrida)",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Andy Betman Vasquez Tapullima",
      "Curso":"Historia Familiar",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154222",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/C4ImxbtnxSb5Af2Zqvf9dV",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fandy.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"HistoriaFamiliar",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"F\u00E9lix Scott Balta Benavides",
      "Curso":"Jesucristo y el Evangelio Sempiterno",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154027",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/JlagIPqzBgK1Vas6sZG2jw",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Ffelix.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"JesucristoyelEvangelioSempiterno",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Joseph Arthur Balta Benavides",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154025",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/JuFngduhUtqKbVANSINqZH",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fjoseph.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":5
   },
   {
      "Hora":"30/12/1899 20:00:00",
      "Maestro":"Joshua Hidalgo Esquivel",
      "Curso":"Libro de Morm\u00F3n 2",
      "EnlaceInscripcion":"https://myinstitute.churchofjesuschrist.org/classes?add=1154028",
      "EnlaceWhatsapp":"https://chat.whatsapp.com/DwPLxXUCqBh2v859sFcUkf",
      "EnlaceFoto":"https://firebasestorage.googleapis.com/v0/b/ils-horario.appspot.com/o/Cursos%2Fjoshua.jpeg?alt=media\u0026token=552712e3-4fc4-4d54-bbec-94c52dd2a00c",
      "Turno":"PM",
      "Dia":"Sabado",
      "CursoCorto":"LibrodeMorm\u00F3n2",
      "NumeroDia":5
   }
]
